export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const ADD_BUS = 'ADD_BUS';
export const UPDATE_BUS = 'UPDATE_BUS';
export const DELETE_BUS = 'DELETE_BUS';
export const GET_BUS_ERROR = 'GET_BUS_ERROR';
export const ADD_TICKET = 'ADD_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR';
export const VIEW_BUSES_REQUEST = 'VIEW_BUSES_REQUEST';
export const VIEW_BUSES_SUCCESS = 'VIEW_BUSES_SUCCESS';
export const VIEW_BUSES_FAILURE = 'VIEW_BUSES_FAILURE';
export const VIEW_TICKETS_REQUEST = 'VIEW_TICKETS_REQUEST';
export const VIEW_TICKETS_SUCCESS = 'VIEW_TICKETS_SUCCESS';
export const VIEW_TICKETS_FAILURE = 'VIEW_TICKETS_FAILURE';
export const PURCHASE_TICKET_REQUEST = 'PURCHASE_TICKET_REQUEST';
export const PURCHASE_TICKET_SUCCESS = 'PURCHASE_TICKET_SUCCESS';
export const PURCHASE_TICKET_FAILURE = 'PURCHASE_TICKET_FAILURE';
export const SEARCH_BUSES = "SEARCH_BUSES";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SEARCH_BUSES_REQUEST = "SEARCH_BUSES_REQUEST";
export const SEARCH_BUSES_SUCCESS = "SEARCH_BUSES_SUCCESS";
export const SEARCH_BUSES_FAILURE = "SEARCH_BUSES_FAILURE";
export const GET_ALL_BUSES = "GET_ALL_BUSES";
export const GET_BUS_BY_ID = "GET_BUS_BY_ID";
// Action Types
export const FETCH_BOOKED_SEATS_REQUEST = 'FETCH_BOOKED_SEATS_REQUEST';
export const FETCH_BOOKED_SEATS_SUCCESS = 'FETCH_BOOKED_SEATS_SUCCESS';
export const FETCH_BOOKED_SEATS_FAILURE = 'FETCH_BOOKED_SEATS_FAILURE';

export const BOOK_SEAT_REQUEST = 'BOOK_SEAT_REQUEST';
export const BOOK_SEAT_SUCCESS = 'BOOK_SEAT_SUCCESS';
export const BOOK_SEAT_FAILURE = 'BOOK_SEAT_FAILURE';


export const ADD_SEAT_TO_CART = 'ADD_SEAT_TO_CART';
export const REMOVE_SEAT_FROM_CART = 'REMOVE_SEAT_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE';

export const UPDATE_USER_STATUS_REQUEST = 'UPDATE_USER_STATUS_REQUEST';
export const UPDATE_USER_STATUS_SUCCESS = 'UPDATE_USER_STATUS_SUCCESS';
export const UPDATE_USER_STATUS_FAILURE = 'UPDATE_USER_STATUS_FAILURE';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const CREATE_USER_REQUEST = 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';


// Ticket action types
export const ADD_TICKET_REQUEST = 'ADD_TICKET_REQUEST';
export const ADD_TICKET_SUCCESS = 'ADD_TICKET_SUCCESS';
export const ADD_TICKET_FAIL = 'ADD_TICKET_FAIL';

export const GET_TICKETS_REQUEST = 'GET_TICKETS_REQUEST';
export const GET_TICKETS_SUCCESS = 'GET_TICKETS_SUCCESS';
export const GET_TICKETS_FAIL = 'GET_TICKETS_FAIL';

export const GET_TICKET_BY_ID_REQUEST = 'GET_TICKET_BY_ID_REQUEST';
export const GET_TICKET_BY_ID_SUCCESS = 'GET_TICKET_BY_ID_SUCCESS';
export const GET_TICKET_BY_ID_FAIL = 'GET_TICKET_BY_ID_FAIL';

export const UPDATE_TICKET_REQUEST = 'UPDATE_TICKET_REQUEST';
export const UPDATE_TICKET_SUCCESS = 'UPDATE_TICKET_SUCCESS';
export const UPDATE_TICKET_FAIL = 'UPDATE_TICKET_FAIL';

export const DELETE_TICKET_REQUEST = 'DELETE_TICKET_REQUEST';
export const DELETE_TICKET_SUCCESS = 'DELETE_TICKET_SUCCESS';
export const DELETE_TICKET_FAIL = 'DELETE_TICKET_FAIL';



