export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGOUT = 'LOGOUT';
export const REFRESH_TOKEN_SUCCESS = 'REFRESH_TOKEN_SUCCESS';
export const ADD_BUS = 'ADD_BUS';
export const UPDATE_BUS = 'UPDATE_BUS';
export const DELETE_BUS = 'DELETE_BUS';
export const GET_BUS_ERROR = 'GET_BUS_ERROR';
export const ADD_TICKET = 'ADD_TICKET';
export const UPDATE_TICKET = 'UPDATE_TICKET';
export const DELETE_TICKET = 'DELETE_TICKET';
export const GET_TICKET_ERROR = 'GET_TICKET_ERROR';
export const VIEW_BUSES_REQUEST = 'VIEW_BUSES_REQUEST';
export const VIEW_BUSES_SUCCESS = 'VIEW_BUSES_SUCCESS';
export const VIEW_BUSES_FAILURE = 'VIEW_BUSES_FAILURE';
export const VIEW_TICKETS_REQUEST = 'VIEW_TICKETS_REQUEST';
export const VIEW_TICKETS_SUCCESS = 'VIEW_TICKETS_SUCCESS';
export const VIEW_TICKETS_FAILURE = 'VIEW_TICKETS_FAILURE';
export const PURCHASE_TICKET_REQUEST = 'PURCHASE_TICKET_REQUEST';
export const PURCHASE_TICKET_SUCCESS = 'PURCHASE_TICKET_SUCCESS';
export const PURCHASE_TICKET_FAILURE = 'PURCHASE_TICKET_FAILURE';
export const SEARCH_BUSES = "SEARCH_BUSES";
export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS";

export const SEARCH_BUSES_REQUEST = "SEARCH_BUSES_REQUEST";
export const SEARCH_BUSES_SUCCESS = "SEARCH_BUSES_SUCCESS";
export const SEARCH_BUSES_FAILURE = "SEARCH_BUSES_FAILURE";
// Action Types
export const FETCH_BOOKED_SEATS_REQUEST = 'FETCH_BOOKED_SEATS_REQUEST';
export const FETCH_BOOKED_SEATS_SUCCESS = 'FETCH_BOOKED_SEATS_SUCCESS';
export const FETCH_BOOKED_SEATS_FAILURE = 'FETCH_BOOKED_SEATS_FAILURE';

export const BOOK_SEAT_REQUEST = 'BOOK_SEAT_REQUEST';
export const BOOK_SEAT_SUCCESS = 'BOOK_SEAT_SUCCESS';
export const BOOK_SEAT_FAILURE = 'BOOK_SEAT_FAILURE';


export const ADD_SEAT_TO_CART = 'ADD_SEAT_TO_CART';
export const REMOVE_SEAT_FROM_CART = 'REMOVE_SEAT_FROM_CART';
export const CLEAR_CART = 'CLEAR_CART';